int signMask(void);
int bitXor(int x, int y);
int negativePart(int x);
int copyByteWithin(int x, int src, int dst);
int logicalShift(int x, int n);
int swapNibblePairs(int x);
int secondLowestZeroBit(int x);
int oddParity(int x);
int rotateRightBits(int x, int n);
int roundEvenPow2(int x, int n);
int midpointTowardFirst(int x, int y);
int isBetweenEitherOrder(int x, int a, int b);
int mul5Sat(int x);
int classifyAdd3(int x, int y, int z);
unsigned floatScaleThreeHalves(unsigned uf);
unsigned floatRoundEven(unsigned uf);
unsigned float_i2f(int x);
int bitCount(int x);
int bitReverse(int x);

int test_signMask(void);
int test_bitXor(int x, int y);
int test_negativePart(int x);
int test_copyByteWithin(int x, int src, int dst);
int test_logicalShift(int x, int n);
int test_swapNibblePairs(int x);
int test_secondLowestZeroBit(int x);
int test_oddParity(int x);
int test_rotateRightBits(int x, int n);
int test_roundEvenPow2(int x, int n);
int test_midpointTowardFirst(int x, int y);
int test_isBetweenEitherOrder(int x, int a, int b);
int test_mul5Sat(int x);
int test_classifyAdd3(int x, int y, int z);
unsigned test_floatScaleThreeHalves(unsigned uf);
unsigned test_floatRoundEven(unsigned uf);
unsigned test_float_i2f(int x);
int test_bitCount(int x);
int test_bitReverse(int x);
